apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: western-sparrow-go 
  janus-idp.io/tekton: western-sparrow-go
  backstage.io/kubernetes-id: western-sparrow-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: western-sparrow-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  